version: '3'

services:
  best_admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_BASE_API_URL=https://app.bestelectronics.com.bd/api/v1
        - NEXT_PUBLIC_IMAGE_URL=https://app.bestelectronics.com.bd/api/v1/images
        - NEXT_PUBLIC_SOCKET_URL=https://app.bestelectronics.com.bd/api/v1
    ports:
      - 3004:3004
    container_name: best_admin
 

