version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=https://app.bestelectronics.com.bd/api/v1
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
